export const CHANGE_HUE = 'CHANGE_HUE';
export const CHANGE_SATURATION = 'CHANGE_SATURATION';
export const CHANGE_LIGHTNESS = 'CHANGE_LIGHTNESS';

export const CHANGE_AUTO_FONT_COLOR = 'CHANGE_AUTO_FONT_COLOR';
export const CHANGE_FONT_COLOR = 'CHANGE_FONT_COLOR';

export const CHANGE_VISIBLE_SHADOWS = 'CHANGE_VISIBLE_SHADOWS';
export const CHANGE_COLORED_SHADOWS = 'CHANGE_COLORED_SHADOWS'